name: ade
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohttp=3.8.3=py38h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - async-timeout=4.0.2=py38h06a4308_0
  - attrs=22.1.0=py38h06a4308_0
  - blas=1.0=mkl
  - blinker=1.4=py38h06a4308_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38h06a4308_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py38h5eee18b_0
  - ftfy=5.8=py_0
  - gensim=4.3.0=py38h6a678d5_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.19.4=h568e23c_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.9=h16c4e8d_3
  - libprotobuf=3.20.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py38h06a4308_0
  - matplotlib=3.7.1=py38h06a4308_0
  - matplotlib-base=3.7.1=py38h417a72b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=6.0.2=py38h5eee18b_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=22.0=py38h06a4308_0
  - pcre=8.45=h295c915_0
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.0.1=py38h06a4308_0
  - ply=3.11=py38_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38h06a4308_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.7=py38h6a678d5_1
  - pyqt5-sip=12.11.0=py38h6a678d5_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py38h5eee18b_1
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - readline=8.2=h5eee18b_0
  - regex=2022.7.9=py38h5eee18b_0
  - requests=2.28.1=py38h06a4308_1
  - scipy=1.10.0=py38h14f4228_1
  - sip=6.6.2=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py38h06a4308_0
  - sqlite=3.41.1=h5eee18b_0
  - tensorboard-plugin-wit=1.8.1=py38h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - tornado=6.2=py38h5eee18b_0
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.38.4=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py38h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - cachetools==5.3.0
    - cvxopt==1.3.0
    - cvxpy==1.3.0
    - ecos==2.0.12
    - google-auth==2.16.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.3
    - importlib-metadata==6.0.0
    - markupsafe==2.1.2
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - osqp==0.6.2.post8
    - protobuf==4.22.1
    - pyasn1-modules==0.2.8
    - qdldl==0.1.5.post3
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scs==3.2.2
    - setuptools==64.0.2
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tqdm==4.65.0
    - werkzeug==2.2.3
    - zipp==3.15.0
    - qpth==0.0.15
